name: Build & Push n8n Custom Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: write

jobs:
  check-latest-version:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get_version.outputs.version }}
      should_build: ${{ steps.check_update.outputs.should_build }}
    steps:
      - name: Getting latest n8n version
        id: get_version
        run: |
          VERSION=$(curl -sS https://api.github.com/repos/n8n-io/n8n/releases/latest | jq -r '.tag_name | sub("^n8n@"; "")')
          echo "Latest n8n version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check for n8n updates
        id: check_update
        run: |
          CURRENT_VERSION=$(curl -sS https://api.github.com/user/packages/container/n8n/versions | jq -r '.tags[0]')
          echo "Current version: $CURRENT_VERSION"
          if [[ "$CURRENT_VERSION" != "$VERSION" ]]; then
            echo "Found new version! building new image..."
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "No new version."
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

  build-and-push:
    needs: check-latest-version
    if: needs.check-latest-version.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/gorlikitsme/n8n:${{ needs.check-latest-version.outputs.latest_version }}
            ghcr.io/gorlikitsme/n8n:latest
